### PR TITLE
Stop WebView in onPause.

### PR DESCRIPTION
**Pull request by Low012**
This change makes sure that video is stopped when screen is turned off (for example via power button).

### CODE REVIEW

**Comment by martykan** [comment]
That is not really a desirable behavior. Many people (including myself) use it for background playback. I will add in a settings activity, where you will be able to optionally enable it.

**Comment by Low012** [comment]
Then you are probably just listening to it without watching it, right? That's a use case that did not come to my mind. I usually just watch a video and it annoys me if I have to unlock my phone again (8 digit pin) just to turn off the video because I forgot that it does not stop automatically.

Adding it to the settings is a great solution!

**Comment by ildar** [comment]
That's the "Play Audio only" option found in VLC and NewPipe.
I think the _video_ should be paused.

**Comment by martykan** [comment]
I solved this by adding an option to the menu to disable background play.

**Pull request closed without merging**
