### PR TITLE
Fix: Toggle FLAG_KEEP_SCREEN_ON to prevent the screen from timing out…

### PR DESCRIPTION
**Pull request by BaFin**
… while video is playing.

### CODE REVIEW

**Comment by BaFin** [comment]
Best practice is to use getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON). However these methods are both static, hence directly using the View class.

This fix does not work if the video is autoplayed (callback for onload required).

**Comment by Rush** [comment]
I wonder, why aren't these PRs getting merged? @BaFin do you have an apk with your change?

**Comment by BaFin** [comment]
I think this project is not being maintained anymore.

**Comment by lramage94** [comment]
Has anyone tried contacting the author?

**Pull request closed without merging**
